### ISSUE TITLE
Separate with variables secrets.yml

### ISSUE THREAD

**Issue by mperezv** [coopdevs/timeoverflow-provisioning#153]
We have a whole encrypted file on `inventory/host_vars/staging.timeoverflow.org/secrets.yml`, why don't we do like the other secrets.yml and split it in variables?

**Comment by sauloperez** [comment]
Yes, we should. It's much better. This is already tracked in https://github.com/coopdevs/timeoverflow-provisioning/issues/146 so I'm closing this because it's a duplicate.
