### ISSUE TITLE
Refactor dangerous query in cron job

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow-provisioning#24]
The definition of the `send_recent_posts_to_online_members` cron job fetches all organizations present in the DB in https://github.com/coopdevs/timeoverflow-provisioning/pull/23#discussion-diff-165091771R16, which will surely blow up our database sooner or later.

We must do this differently and at least process them in batches.

**Comment by markets** [comment]
@sauloperez fixed in https://github.com/coopdevs/timeoverflow/pull/401

**Comment by mperezv** [comment]
Fixed [here](https://github.com/coopdevs/timeoverflow/pull/401).

**Comment by markets** [comment]
Thanks @mperezv! yep that was fixed in the linked PR, but not yet `tested -> merged -> deployed`.
