### ISSUE TITLE
Add SKYLIGHT_AUTHENTICATION env var in production

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow-provisioning#26]
In order for https://github.com/coopdevs/timeoverflow/pull/322 to work, we need to make the `SKYLIGHT_AUTHENTICATION` env var available in production with the appropriate value. More details in #322 .

**Comment by mperezv** [comment]
Solved [here](https://github.com/coopdevs/timeoverflow-provisioning/blob/c7eb5d7a2a7c97c0009bcaf3e38c389e72c40509/roles/common/templates/default.j2#L9)?

**Comment by sauloperez** [comment]
Yep. And the actual proof is https://github.com/coopdevs/timeoverflow-provisioning/blob/master/inventory/host_vars/timeoverflow.org/secrets.yml#L34
