### ISSUE TITLE
elasticsearch is not properly installed with vagrant

### ISSUE THREAD

**Issue by elmendalerenda** [coopdevs/timeoverflow-provisioning#4]
After provisioning a vagrant box, elasticsearch is not started:

``` bash
$ sudo systemctl status elasticsearch
● elasticsearch.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

Although the provisioning log doesn't throw any error, there are missing files, for example /etc/init.d/elasticsearch_elasticsearch

**Comment by enricostano** [comment]
This should be fixed adding this step to the documentation:

```
git submodule update --init --recursive
```

this needs to be run before you provision the machine.

**Comment by elmendalerenda** [comment]
I tried running the command before provisioning but the result is the same. After running the git submodule I saw that indeed ansible is running some task about elasticsearch. The result is the same, though, looks that there are some missing scripts

**Comment by enricostano** [comment]
Maybe we should try with a fresh new VM, just in case Ansible stores some state somewhere and keep convinced that it installed that role... :disappointed: 

In my case, using [LXC containers](https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-with-LXC-for-GNU-Linux#ansible-setup), I just have to provision again and the missing role gets installed.

We can make some debugging there. Thanks for opening the issue!

**Comment by elmendalerenda** [comment]
I was executing a wrong command, this is the correct one and elasticsearch works

``` bash
$> sudo systemctl status elasticsearch_elasticsearch.service 
● elasticsearch_elasticsearch.service - Elasticsearch-elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch_elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since vie 2016-09-30 09:03:53 UTC; 54min ago
     Docs: http://www.elastic.co
 Main PID: 721 (java)
   Memory: 209.2M
      CPU: 17.148s
   CGroup: /system.slice/elasticsearch_elasticsearch.service
           └─721 /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction...
```
