### ISSUE TITLE
Use sys-admins-role

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow-provisioning#46]
https://github.com/coopdevs/sys-admins-role

Instead of https://github.com/coopdevs/timeoverflow-provisioning/tree/master/roles/sys_admins

Also check:
https://github.com/coopdevs/timeoverflow-provisioning/blob/master/roles/common/tasks/users.yml
https://github.com/coopdevs/timeoverflow-provisioning/blob/master/roles/common/tasks/groups.yml

**Comment by mperezv** [comment]
Using it already --> https://github.com/coopdevs/timeoverflow-provisioning/blob/master/playbooks/sys_admins.yml
