### ISSUE TITLE
Fix the patch version of ruby 

### ISSUE THREAD

**Issue by elmendalerenda** [coopdevs/timeoverflow-provisioning#5]
The current [configured repository](https://github.com/coopdevs/timeoverflow-provisioning/blob/master/roles/common/tasks/install_packages.yml#L15)  removes the package of the patch version when a new one is released. That is why the ruby version in pro and dev environments are not the same.

**Comment by enricostano** [comment]
We'll need to switch to `rbenv` ASAP in both `production` and `development`.
