### ISSUE TITLE
Specify deploy path in a variable

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow-provisioning#50]
In `development` we use `/var/www/timeoverflow` while in `staging` we use `/var/www/timeoverflow/current`.

This is needed to make Sidekiq systemd unit to work in `development`:
https://github.com/coopdevs/timeoverflow-provisioning/blob/e959d91089aafcd99ab1e18e9d3f2f61a39a031b/roles/background_jobs/templates/sidekiq_service.j2#L11

But probably worth using the variable in other places too (unicorn, etc)

**Comment by mperezv** [comment]
Solved by @sauloperez [here](https://github.com/coopdevs/timeoverflow-provisioning/commit/ef2f4b6a5a07cc544fb2616b8f5cff9ef291c31d#diff-2bedacfd194155da5ac329ed6bff4aa5).
