### ISSUE TITLE
Error on playbook "Ensure PostgreSQL databases are present"

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow-provisioning#57]
TASK [geerlingguy.postgresql : Ensure PostgreSQL databases are present.] ****************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ProgrammingError: role "timeoverflow" does not exist
failed: [local.timeoverflow.org] (item={u'owner': u'timeoverflow', u'lc_collate': u'es_ES.UTF-8', u'name': u'timeoverflow_development', u'lc_ctype': u'es_ES.UTF-8'}) => {"changed": false, "item": {"lc_collate": "es_ES.UTF-8", "lc_ctype": "es_ES.UTF-8", "name": "timeoverflow_development", "owner": "timeoverflow"}, "msg": "Database query failed: role \"timeoverflow\" does not exist\n"}
	to retry, use: --limit @/home/slimbook/dev/timeoverflow-provisioning/playbooks/provision.retry

![2019-02-14-193428_1960x2160_scrot](https://user-images.githubusercontent.com/2297137/52809108-ced47f00-308f-11e9-9e07-583e3b5379ff.png)

**Comment by sseerrggii** [comment]
was a error on documentation, fixed :) https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-with-LXC-for-GNU-Linux

**Comment by enricostano** [comment]
No, it wasn't a doc problem, we need to fix it https://github.com/coopdevs/timeoverflow-provisioning/pull/59
