### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow-provisioning#58]
Following this guide
https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-with-LXC-for-GNU-Linux

on [step 3](https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-with-LXC-for-GNU-Linux#step-3-backend-application-setup-ruby-on-rails).2

`bundle install --path vendor/bundle`

I have this error.

```
Errno::EACCES: Permission denied @ rb_sysopen - /var/www/timeoverflow/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.12/.gitignore
An error occurred while installing bcrypt (3.1.12), and Bundler cannot continue.
Make sure that `gem install bcrypt -v '3.1.12' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  devise was resolved to 4.5.0, which depends on
    bcrypt

```

**Comment by andresgutgon** [comment]
Did you tried to run this command?
gem install bcrypt -v '3.1.12' --source 'https://rubygems.org/'

Sometimes installing failing gem alone does the work

**Comment by sseerrggii** [comment]
Yes @andresgutgon I tried and the gem was installed but when I repeat 

`bundle install --path vendor/bundle`

I had the same error :disappointed:

**Comment by sseerrggii** [comment]
I fix it with help of @enricostano with

`sudo rm -rf vendor/bundle/`

and after that repeat: 

`bundle install --path vendor/bundle`

**Comment by andresgutgon** [comment]
lol `rm -rf node_modules` @Morantron knows a lot about this :trollface:
