### ISSUE TITLE
Instructions to share a folder in vagrant

### ISSUE THREAD

**Issue by elmendalerenda** [coopdevs/timeoverflow-provisioning#7]
Contributors usually edit the timeoverflow project outside the vagrant machine, which means they need a way share the folder of the repo. Less experienced contributors that don't fully understand vagrant need a guide to configure the shared folder.

**Comment by enricostano** [comment]
Yes please! :+1: :+1: :+1: 

With LXC is way easier and more performant but we need to implement this for Vagrant VMs too since each developer prefer to use his/her own tools to code.

**Comment by mperezv** [comment]
Fixed [here](https://github.com/coopdevs/timeoverflow-provisioning/commit/68baeed19042095efce5015f3ee2c2516d788133)?
