### ISSUE TITLE
Create custom service for ElasticSearch

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow-provisioning#89]
It turns out that the systemd service the elasticsearch role creates (introduced in https://github.com/coopdevs/timeoverflow-provisioning/pull/82) doesn't work with the old version of ES we're running in production, 2.4.6.

We can either follow the approach we followed in https://github.com/coopdevs/timeoverflow-provisioning/pull/84 or find out if we can skip the service creation by using a variable and do it ourselves.

If we follow the second approach, please provide also these variables we've been playing with:

```
es_version: 2.4.6
es_use_repository: false
```

**Comment by sauloperez** [comment]
I just provisioned with the branch `install-ES-2.6.4` and indeed the systemd complaints about the unit file:

```
● timeoverflow_elasticsearch.service - Elasticsearch-timeoverflow
   Loaded: loaded (/usr/lib/systemd/system/timeoverflow_elasticsearch.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-10-09 16:48:36 CEST; 3min 16s ago
     Docs: http://www.elastic.co
 Main PID: 3565 (code=exited, status=64)

Oct 09 16:48:35 staging systemd[1]: Starting Elasticsearch-timeoverflow...
Oct 09 16:48:35 staging systemd[1]: Started Elasticsearch-timeoverflow.
Oct 09 16:48:36 staging elasticsearch[3565]: ERROR: Parameter [-Edefault.path.data=/var/lib/elasticsearch/staging.timeoverflow.org-timeoverflow]does not start with --
Oct 09 16:48:36 staging systemd[1]: timeoverflow_elasticsearch.service: Main process exited, code=exited, status=64/n/a
Oct 09 16:48:36 staging systemd[1]: timeoverflow_elasticsearch.service: Failed with result 'exit-code'.
```

I can confirm the right version was installed:

```
$ ll /tmp/elasticsearch-2.4.6.deb 
-rw-r--r-- 1 root root 27234396 Oct  9 16:37 /tmp/elasticsearch-2.4.6.deb
```

There's no other way than writing a custom unit ourselves, I'm afraid.

**Comment by markets** [comment]
@sauloperez I think this issue will be deprecated by https://github.com/coopdevs/timeoverflow/issues/551. Just adding the comment for linking both issues.

**Comment by sauloperez** [comment]
I actually think we implemented the service to provision the new production server with the current ES version but I didn't check.

**Comment by markets** [comment]
@sauloperez so time close this?

**Comment by sauloperez** [comment]
Yep, confirmed
